[package]
name = "test-rust-package"
version = "0.1.0"
authors = ["Ammar Askar <ammar@ammaraskar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
