name: Test Images

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build base rudra image
        run: cd rudra && docker build . -t rudra

      - name: Build artifact image
        run: docker build . -t rudra-artifact

      - name: Set up fixed rudra runner home
        run: mkdir ~/rudra-home && rudra/setup_rudra_runner_home_fixed.py ~/rudra-home
