name: Generate Artifact Release

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add commit hash to README
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s/XXXXX/$GIT_HASH/" README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
